# Generated by Django 4.2 on 2024-01-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='adherent',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='code_auteur',
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
        migrations.DeleteModel(
            name='Auteur',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
